blank_issues_enabled: true
contact_links:
  - name: 📚 Documentation
    url: https://github.com/defaultroot-ai/cabinete/tree/main/docs
    about: Check our comprehensive documentation
  - name: 💬 Discussions
    url: https://github.com/defaultroot-ai/cabinete/discussions
    about: Ask questions and discuss features
  - name: 🔒 Security Issue
    url: https://github.com/defaultroot-ai/cabinete/security
    about: Report a security vulnerability privately

