name: WordPress Plugin Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
    
    - name: Check PHP syntax
      run: find . -name "*.php" -exec php -l {} \;
    
    - name: WordPress Coding Standards
      run: echo "PHPCS check would run here"
  
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1']
        wordpress-version: ['5.9', '6.0', '6.4']
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mysqli, mbstring
    
    - name: Test WordPress ${{ matrix.wordpress-version }} compatibility
      run: echo "WordPress compatibility tests would run here"

